events {
    worker_connections 1024;
}

http {
    upstream backend_services {
        server auth-service:8000;
        server ticket-service:8001;
        server chat-service:8002;
        server knowledge-service:8003;
    }
}
