server {
    listen 80;
    server_name _;

    location / {
        add_header Access-Control-Allow-Origin *;
        root /usr/share/nginx/html/assets;
        try_files /remoteEntry.js =404;
    }

    location /remoteEntry.js {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=3600";
    }

    location ~* \.(js|css)$ {
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=31536000";
    }
}
