name: Deploy Remote - Auth

on:
  push:
    branches: [main]
    paths:
      - "apps/remote-auth/**"
      - "packages/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm --filter remote-auth test

      - name: Build Asset
        run: pnpm --filter remote-auth build

      - name: Upload to S3 CDN
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: "./apps/remote-auth/dist/assets"
          destination_dir: "remotes/auth"
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Purge CloudFront Cache
        uses: awslabs/aws-cloudfront-action@v1
        with:
          distribution-id: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          paths: "/remotes/auth/*"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}